import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Nav from "@/components/nav/Nav";

const interRegular = localFont({
  src: "./fonts/Inter18pt-Regular.woff",
  variable: "--font-inter-regular",
  weight: "400",
});

const interMedium = localFont({
  src: "./fonts/Inter18pt-Medium.woff",
  variable: "--font-inter-medium",
  weight: "500",
});

const interSemibold = localFont({
  src: "./fonts/Inter18pt-SemiBold.woff",
  variable: "--font-inter-semibold",
  weight: "600",
});

const interBold = localFont({
  src: "./fonts/Inter18pt-Bold.woff",
  variable: "--font-inter-bold",
  weight: "700",
});

const suranna = localFont({
  src: "./fonts/Suranna.woff",
  variable: "--font-suranna-regular",
  weight: "400",
});

const fasthand = localFont({
  src: "./fonts/Fasthand-Regular.woff",
  variable: "--font-fasthand-regular",
  weight: "400"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${interRegular.variable} ${interBold.variable} ${interMedium.variable} ${interSemibold.variable} ${suranna.variable} ${fasthand.variable} antialiased flex flex-col min-h-dvh`}
      >
        <Nav />
        {children}
      </body>
    </html>
  );
}
